# Generated by Django 5.1.1 on 2024-10-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('edition', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=20)),
                ('Pass_word', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
