# Generated by Django 5.1.1 on 2024-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='issued_books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('edition', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('issued_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issued_books',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='users',
            name='contact_details',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
